### ISSUE TITLE
Undefined function message_stripe_error_to_admin()

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_stripepayment#1]
The file enrol/stripepayment/charge.php seems to call `message_stripe_error_to_admin()` in certain cases. However, there is no such a function defined (also note that such a function name violates the naming conventions).

**Comment by mudrd8mz** [comment]
Ok, there is `message_stripepayment_error_to_admin()` defined at the bottom of that file - not the diff in the names. Plus, better to follow the naming conventions even for helper functions like this.

**Comment by parthajeet** [comment]
Thanks for the notification. We have fixed the mentioned issue.

Regards,
ParthaJeet~
