### ISSUE TITLE
Callback error only with Stripe Live Keys

### ISSUE THREAD

**Issue by nicolalopatriello** [dualcube/moodle-enrol_stripepayment#103]
Hi,
After payment callback i receive this error during redirect to Moodle website:

```
Something else happened, completely unrelated to Stripe{"exception":"invalid_response_exception","errorcode":"invalidresponse","message":"E' stato individuato un valore non valido nella risposta (Only arrays\/objects accepted. The bad value is: '')","debuginfo":"Only arrays\/objects accepted. The bad value is: ''"}
```

This happen only in Live mode with Live Stripe keys instead with Test Keys all works properly. 

The plugin version is 3.3.3

Can anyone help me?

Thanks.

**Comment by moumitahalder** [comment]
Hi, please use the latest version of stripe plugin.

**Comment by gaioso** [comment]
Hi, I have the same error with plugin version 3.4.1.

Anyone else with this problem? Thanks
