### ISSUE TITLE
New Stripe Api Version Have Problem

### ISSUE THREAD

**Issue by mzr111** [dualcube/moodle-enrol_stripepayment#107]
API version
[2022-08-01](https://stripe.com/docs/upgrades#2022-08-01)

Key — 300032cd-c500-42c7-984c-faea625eb6b6
invalid_request_error

You cannot use line_items.amount, line_items.currency, line_items.name, line_items.description, or line_items.images in this API version. Please use line_items.price or line_items.price_data. Please see https://stripe.com/docs/payments/checkout/migrating-prices for more information.

**Comment by moumitahalder** [comment]
Hi @mzr111, after hearing from you we checked this on our end , as you can see we didn't face any such issue : https://watch.screencastify.com/v/ZEJtuP5eebg8ZgTByCyt

Now that you are facing this issue, can you please share a video of the flow?

**Comment by mzr111** [comment]
Dear moumitahder

Here I  attach to you what I am facing. Tq for responding
 stripeproblemwithnewapiversion.mp4
<https://drive.google.com/file/d/1M8tDNWoSjQiLh0GG6baqOMM2EObHW3fG/view?usp=drive_web>

**Comment by mzr111** [comment]
The only problem with my new stripe account. THis is because my new account
uses the new stripe api version 2022-08-01 meanwhile my old account stripe
using api version 2020-08-27.

**Comment by mzr111** [comment]
(07:34:27 AM) Iane: Since you've just created your Stripe account
recently, the API defaulted to the latest version which is the 2022-08-01
version. However, the parameters you used as per this log
req_E206z2k7Wvyrt0 is an old parameter and does not match the latest API
version.
(07:34:48 AM) Iane: Our API is telling you to use the line_items.price or
line_items.price_data instead.
(07:35:02 AM) Iane:
https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items-data-price
(07:35:40 AM) Iane: You can also see in this link that all the parameters
that you're currently using have been deleted from the current version of
the API: https://stripe.com/docs/upgrades#2022-08-01
(07:54:47 AM) Iane: https://stripe.com/docs/api#versioning

[image: image.png]

May i know in which php plugin file can i send the stripe version header in
your coding? Appreciate your help. TQ

**Comment by mzr111** [comment]
I managed to make it working. I make modification on this file
*/moodle/enrol/stripepayment/Stripe/lib/Stripe.php
by putting the api version*

*  /** @var null|string The version of the Stripe API to use for requests.
*/    public static $apiVersion = '2020-08-27'; *

**Comment by moumitahalder** [comment]
Hi @mzr111 please use latest version of the plugin.

**Comment by mzr111** [comment]
Tq. I appreciate it.
