### ISSUE TITLE
Moodle can't process to checkout page

### ISSUE THREAD

**Issue by vaiz777** [dualcube/moodle-enrol_stripepayment#109]
I hade activated the test API and configure it but when try a test give result like below:

You cannot use line_items.amount, line_items.currency, line_items.name, line_items.description, or line_items.images in this API version. Please use line_items.price or line_items.price_data. Please see https://stripe.com/docs/payments/checkout/migrating-prices for more information.

**Comment by smasih-sylla** [comment]
same issue encountered to me, let me know if any solution was found @vaiz777

**Comment by bit9labs** [comment]
+1

**Comment by moumitahalder** [comment]
Hi @bit9labs @vaiz777 , can you please explain one small piece of information? Is this error happening for all the products?
