### ISSUE TITLE
100% off coupon does not get redeemed in Stripe

### ISSUE THREAD

**Issue by jimcrammond** [dualcube/moodle-enrol_stripepayment#111]
In version 3.3.4 when a 100% off coupon is applied the stripepayment_free_enrolsettings function in externallib.php is called. But this function is missing the code to create the customer in Stripe or update the customer with the coupon. As a result the coupon is not redeemed. If you have a coupon with the limited number of redemptions then this is a problem. 

I have a patch for this issue:
[stripepayment-free-enrol.patch](https://github.com/dualcube/moodle-enrol_stripepayment/files/10506056/stripepayment-free-enrol.patch)

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
