### ISSUE TITLE
Redirection fails after stripe payment - access to <site> is denied

### ISSUE THREAD

**Issue by jimcrammond** [dualcube/moodle-enrol_stripepayment#112]
Others have reported this issue too. On attempting to return from the stripe payment web page, an attempt to redirect to <wwwroot>/webservice/rest/server.php?wstoken=text&wsfunction=moodle_stripepayment_success_stripe_url&moodlewsrestformat=json&session_id=cs_test_a1WXI4rp83Ci8EnAFYgWPP497gVJo4I4EGA7r9NNJ54LDVT6CbOw1&courseid=7&couponid=TEST2&user_id=357&instance_id=23

is made which should run the stripepayment_success_stripe_url to finish the enrolment. But this instead produces an HTTP 403 error.

**Comment by jimcrammond** [comment]
I got further by enabling web services in "site administration->advanced settings" and then enabling the "rest" protocol.
Now it fails with the exception of missing token. Not clear how this is generated.

It seems there is a set of new configuration steps required with 3.3.4 that are not documented.

**Comment by moumitahalder** [comment]
You need to create Token for stripe : https://jhn4wdmbd4.vmaker.com/record/UMr80J688kjRahxg

Kindly add this and check again.

Please do keep us posted.

**Comment by jimcrammond** [comment]
This was what I was missing, but I then ran into a couple of bugs. 

1. On returning from the stripe page, I got a "paymentsorry" message. This was because the call to is_enrolled() in success_stripe_url is called with a null user and therefore is_enrolled() tries the $USER global which is set to the admin user as per the token setting (who is not enrolled).  Passing $user to is_enrolled() fixes this.
2. The test for coupon fails and therefore the coupon is not applied in stripe. Changing the test "data->coupon_id != 0" to "data->coupon_id != '0'" fixes this. I.e. put quotes around the zero. (I realize the zero is what stripe returns in the callback when there is no coupon but it is a string not an integer.)
3. In some tests I got an exception displayed rather than the paymentsorry message because the $OUTPUT variable was not set- it should be declared in the list of globals at the beginning of success_stripe_url. Not sure why it worked sometimes..

**Comment by jimcrammond** [comment]
This patch addresses the issues I found in the success_stripe_url function in the previous comment.

[stripepayment-success-url.patch](https://github.com/dualcube/moodle-enrol_stripepayment/files/10552498/stripepayment-success-url.patch)

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
