### ISSUE TITLE
In stripe dashboard, payment description no longer shows course name

### ISSUE THREAD

**Issue by jimcrammond** [dualcube/moodle-enrol_stripepayment#114]
In the 3.2.1 version of the plugin, in the payments section of the stripe dashboard, the Description field contains the course name. It was therefore easy to see which courses people are buying. With the 3.3.4 version, the Description field is filled with the payment intent ID. This is not at all helpful.

**Comment by jimcrammond** [comment]
It should be noted that in the POST /v1/checkout/sessions call, the request body does contain line_items -> description that is set to the coursename, but the response body has description set to null

**Comment by moumitahalder** [comment]
@jimcrammond, we will add this support in our next update.

**Comment by jimcrammond** [comment]
Adding the following argument to the Checkout Session create() call will resolve this:

'payment_intent_data' => ['description' => $description ],

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
