### ISSUE TITLE
Error Message after Card Payment

### ISSUE THREAD

**Issue by lucas-fath** [dualcube/moodle-enrol_stripepayment#118]
Hello

We are currently facing the issue that we get an error message after paying for a course with a test credit card. I have attached a step-by-step video of this issue. 

We are currently using Moodle Workplace 3.11.6 and enrol_stripepayment 3.3.4.

[screen-capture.webm](https://user-images.githubusercontent.com/121166666/225838935-eab51229-3a71-405c-85d1-9685d985c572.webm)

Is there a way to fix that? 

Kind Regards
Lucas Fath

**Comment by moumitahalder** [comment]
Hi @lucas-fath, our team is looking into this.

Kindly provide them some time.

**Comment by kundandualcube** [comment]
Hello..
I checked your issue but I am unable to find out this issue from my end. 
To know further I would need your stripe payment  Event data , can you please share the details.
=> You can get the Event data from stripe.com->payments ->(search for the particular payment from which you got the error) -> and at the bottom of the page you can get all Event data share all which have error or failed .

**Comment by lucas-fath** [comment]
Hi, sorry for the long response time. Our colleague unfortunately didn't find the time to export the event.
I just tried to set up my own stripe account and switched out the keys with mine.

Unfortunately now nothing happens when we click the "buy now" button. It loads for a short time and then just goes back to displaying "Buy now". However if I call the URL that get's called in the Networks tab of the devtools (Request URL: https://academy-test.snom.com/lib/ajax/service.php?sesskey=8DegVgGmly&info=moodle_stripepayment_stripe_js_settings
) I get this message: {"error":"Coding error detected, it must be fixed by a programmer: Invalid json in request: Syntax error","errorcode":"codingerror","stacktrace":"* line 63 of \/lib\/ajax\/service.php: coding_exception thrown\n","debuginfo":"\nError code: codingerror","reproductionlink":"https:\/\/academy-test.snom.com\/"}

Is this a setup issue of the plugin?

Thanks for your help and sorry again for the long response time and any inconveniences this may have caused.

Greetings
Lucas

**Comment by kundandualcube** [comment]
it's solved and added in the latest version, please check it and let us know that, it's solve your issue or not.
