### ISSUE TITLE
Management interface inside Moodle for all Stripe payments

### ISSUE THREAD

**Issue by mcwe** [dualcube/moodle-enrol_stripepayment#12]
The ability to see all Stripe payments within Moodle and have a reporting feature there. Is this something that is planned?

**Comment by parthajeet** [comment]
Hello,

This feature needs to be done as a reporting plugin. As of now we do not have any update but independently the plugin can be customised as per the requirement.

Regards,
Parthajeet~

**Comment by mcwe** [comment]
Hi Parthajeet,

Please contact me at mboe at mcwe dot com. We would like to have these 3 customizations made and wonder if you could make them for us.

Thank you
