### ISSUE TITLE
After installing: Exception - Class 'admin_setting_requiredtext' not found

### ISSUE THREAD

**Issue by aalcaine** [dualcube/moodle-enrol_stripepayment#122]
It's impossible to use Moodle, the only solution is to remove the plugin. Could downgrade deleting the folder from moodle and downloading release 2023030700 of the plugin.

Using Moodle 3.10.10 (Build: 20220314)

**Comment by JavierStructuralia** [comment]
The class "admin_setting_requiredtext" is present in the /lib/adminlib.php file, in Moolde 4.2 ( https://github.com/moodle/moodle/blob/MOODLE_402_STABLE/lib/adminlib.php ) , but not in 3.11 ( https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/lib/adminlib.php )

I changed the line #499 of the /enrol/stripepayment/lib.php file in this way:

From:
class admin_enrol_stripepayment_configtext extends admin_setting_requiredtext {
To:
class admin_enrol_stripepayment_configtext extends admin_setting_configtext {
