### ISSUE TITLE
Enabling a custom welcome message

### ISSUE THREAD

**Issue by jimcrammond** [dualcube/moodle-enrol_stripepayment#128]
Please consider incorporating the attached patch for enabling a custom welcome message to be generated to email the user on enrolment. The patch is modeled on identical functionality in the self enrolment plugin. 

The patch itself is built on version 3.3.5 but will apply correctly with version 3.4.1 and 3.4.2.

[stripepayment-welcome-msg.patch](https://github.com/dualcube/moodle-enrol_stripepayment/files/11667337/stripepayment-welcome-msg.patch)

**Comment by moumitahalder** [comment]
@jimcrammond, our team will look into this. We will keep you posted.

**Comment by sangeeyeah** [comment]
Hi Team, When installed on Ubuntu + Apache + PHP 8.2 FPM FastCGI + Moodle 4.1.3, the following error is generated.

{"exception":"Error","message":"Attempt to assign property \"course\" on null"}

The enrolment is successful, but this error message is displayed in text format. Perhaps this is a PHP 8.2 compatibility issue?

**Comment by kundandualcube** [comment]
hello, @sangeeyeah we are happy to see you for using our plugin. For your kind information we resolved your issue on last update . please use stripe version -[3.4.2 (Build: [2023060200)]](https://moodle.org/plugins/enrol_stripepayment/3.4.2-build-2023060200/29341). And let us know, if you still have the issue. 

thanks again...

**Comment by jimcrammond** [comment]
The last two comments are nothing to do with issue #128 and should either be associated with #issue 127 or filed as a separate ticket
