### ISSUE TITLE
Stripe error with Moodle

### ISSUE THREAD

**Issue by fesaner** [dualcube/moodle-enrol_stripepayment#13]
We have been using Stripe with Moodle for some time.  Shortly after upgrading to Moodle 3.2.3+ (Build: 20170601),  users began getting the following error message, "Something else happened, completely unrelated to Stripe." 
The error is generated from <site url>/enrol/stripepayment/charge.php.  I looked at the code and the error is the general catch-all error at the end of the try-catch code.
I tried enabling Moodle debugging, but no error messages were generated.
We are using Stripe plugin 1.0 (Build: 2015112818) (2015112804)
Our email server is working and Moodle messages are sent out.

Any assistance is appreciated.

Thanks,
Floyd Saner

**Comment by fesaner** [comment]
Bump ... any ideas or comments?

**Comment by parthajeet** [comment]
Hello,

We have checked again, but didn't get this issue. Can you once check your "Stripe Secret Key" and "Stripe Publishable Key".

Thanks,
Parthajeet~

**Comment by fesaner** [comment]
Thanks for checking.  I did some more error analysis and got the following error message:

"Something else happened, completely unrelated to Stripe exception 'Exception' with message 'Stripe needs the Multibyte String PHP extension.' in /var/www/moodle/enrol/stripepayment/Stripe/lib/Stripe.php:13 Stack trace: #0 /var/www/moodle/enrol/stripepayment/charge.php(109): require_once() #1 {main}"

We installed the multibyte string extension and now get the following error:
"Invalid parameters were supplied to Stripe's API"

I'm quite certain we have the correct keys - the plugin was working fine until we upgraded to Moodle 3.2.

We are running PHP Version 5.6.31 on Ubuntu 14.04.01
Any other thoughts?  Your help is appreciated.
Floyd

**Comment by fesaner** [comment]
See my comment above.  I checked the keys - they are correct. I get the same error on three different servers running Moodle 3.2.  Using the live keys and the test keys generate the same error.  "Invalid parameters were supplied to Stripe's API"

**Comment by fesaner** [comment]
Sorry - closed the issue by mistake

**Comment by fesaner** [comment]
OK. Closing this for now. The first problem was not having the multi-byte extension installed on PHP.  The second problem was an incorrect charge amount. 
Thanks for giving us your attention.
Floyd Saner

**Comment by parthajeet** [comment]
Thanks, Glad to know that the issue is fixed. 

Regards,
Parthajeet~
