### ISSUE TITLE
Add extra parameter

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-enrol_stripepayment#132]
The data items we need to have passed into Stripe are:

 

Course full name (input name=”fullname”) value e.g. "Pathogen Planet: Diversity and Disease"
Course short name (input name=”shortname”) value e.g. "SMS22005"
Course id number (input name=”idnumber”) value e.g. "EA003"
 

From our initial testing, we find that the course full name already appears in the “description” element of the Stripe payment intent, so no further action is needed on that. Ideally the other two would appear in Stripe in separate metadata elements within the payment intent metadata element, i.e:

 

  "description": "Pathogen Planet: Diversity and Disease",
  "metadata": {

    "projectCode": "SMS22005",

    "productCode": "EA003"

  },

**Comment by kndnsow** [comment]
Adde on latest version
