### ISSUE TITLE
Amount in yen is multiplied by 100 at checkout.

### ISSUE THREAD

**Issue by tenboshi** [dualcube/moodle-enrol_stripepayment#135]
PHP:7.3
Moodle version:4.1
Plugin version: Stripe Payment (enrol_stripepayment) 3.4.4 (Build: 2023101400)

![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/81812109/ee7850a8-8945-4741-8d8b-0b714d5c6f20)

### Course setting: cost: &yen; 1,500
![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/81812109/5bee4f75-5d69-47ab-a9cf-c5c79e37eb6a)

### enroll course: price is correct.
![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/81812109/fdf4af7d-4f58-4af6-9a35-b862ef3f94df)

### but on Checkout: price mutiplied by 100: &yen; 150,000 
![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/81812109/ba91feb0-ea1c-4a89-a6de-8bddc265c218)

### stripe dashboard:  receives multiplied by 100: &yen; 150,000
![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/81812109/671e3837-7893-4fac-b301-171908600a38)

**Comment by moumitahalder** [comment]
Hi @tenboshi, it might happen that stripe is accepting payments in cents.

That's why as you want to receive money 150, hence stripe will receive 150000
Please do contact stripe regarding this.

**Comment by tenboshi** [comment]
Hi @moumitahalder , 
thanks for commenting on my post.

send json data is "150000 JPY". it's already wrong.

```
  "line_items": {
    "0": {
      "price_data": {
        "unit_amount": "150000", 
        "currency": "JPY",


```
