### ISSUE TITLE
Can we add to extra configuration option to support automatic enrolment into groups?

### ISSUE THREAD

**Issue by timhunt** [dualcube/moodle-enrol_stripepayment#14]
Thank you very much for creating the Stripe payment integration.

We have the requirement that users can pay two diffrerent amounts to enter one of our courses, and depending on what they pay, they can access more or less activities. This is almost working. You can add two separate instances of this plugin to the course, and users see something sensible when they try to access the course for the first time:

![image](https://user-images.githubusercontent.com/138653/28886568-dcd340e8-77b1-11e7-915c-763368bdf957.png)

The only thing is, we don't want users to come in with different roles. What we would like is that users get put into different groups depending on how much they pay. (A bit like the way that using self-enrolment with a password, users can be put into different groups depending on which password they enter.) Also, the repeated text "This course requires a payment for entry." is not ideal.

So, would it be OK to add two new options to edit_form.php:

1. 'Add to group' with a drop-down menu where you can select one of the groups in the course (or none). If a group is selected, then when a user enrols, the are automatically added to that group. (This should probably be added just after 'Assign role'. I think we can store the value in customint4.)

2. 'Custom welcome message' with a text input box. If this is blank, we still display the default message get_string('paymentrequired'), but if you enter some text here, that is shown instead. (This should probably be added just after 'Custom instance name'. I think we can store the value in customtext1.)

If you are happy with these changes, then I can probalby write the code, for you to review, in the next few weeks.

Thank you for considering this proposal.

**Comment by parthajeet** [comment]
Hello Tim,

Team DualCube is delighted to receive your proposal. We already feel honoured for our plugin as it drew your attention. Our developers have reviewed the suggestions.

We are sure that these options will add another dimension to our plugin and a much larger audience will appreciate the workflow. Our team is more excited about the part that we will get a chance to work with you. Please let me know when you would like to start. DualCube is at your service if you need anything.

Regards,
Parthajeet~

**Comment by timhunt** [comment]
Thank you for your positive feedback. I hope to do this development in the next week or two, but it is one of several requirements for a project I am working on, and so I cannot predict exactly when.

**Comment by parthajeet** [comment]
Hello Tim,

We completely understand, please take your time. Feel to reach us out if anything is required in between.

Regards,
Parthajeet~
