### ISSUE TITLE
Is it possible to allow specific coupons for specific courses?

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-enrol_stripepayment#142]
Is it possible to allow specific coupons for specific courses?

**Comment by jimcrammond** [comment]
I have a simple patch that enables this functionality if you are interested. It requires adding the courseid as metadata to the coupon. This is then compared with the actual courseid in stripepayment_couponsettings()

**Comment by moumitahalder** [comment]
Jim, Thank you for the update.

We appreciate your prompt response. Should there be any developments or changes in the future, please feel free to reach out.

Have a great day!

**Comment by billyp1970** [comment]
Quick question.  Has this been implimented into the Moodle Stripe Plugin version 3.4.9 (Build: 2025010900)?  If so, Metadata on the Stripe site for the coupon asks for a Key and Value.  Which of these is the course ID and what should the other value be?
