### ISSUE TITLE
display trouble

### ISSUE THREAD

**Issue by jmd87fr** [dualcube/moodle-enrol_stripepayment#144]
Hi,
Moodle 4.4 (Build: 20240422)
Stripe 3.4.6 (Build: 2024041800)
Theme Moove 4.4.1 2024042300

When I use the Stripe Enrollment my course display is "broken" too big :-(
Seen screencast [https://www.loom.com/share/f8a6e4667098483ab455aa531fc4e981?sid=9ce68fc3-f538-4b9a-8ec4-fefb69a809f9](url)

Thanks for help
Jean-Marc

**Comment by jmd87fr** [comment]
https://www.loom.com/share/f8a6e4667098483ab455aa531fc4e981?sid=ad4f2800-f1ab-4b43-b219-867d99ce1777

**Comment by moumitahalder** [comment]
Hi @jmd87fr , it seems like some conflict with the theme.

However to be sure, can you please remove stripe as enrollment method for this course and check again. let us know whether the issue is still there.

**Comment by jmd87fr** [comment]
> Hi @jmd87fr , it seems like some conflict with the theme.
> 
> However to be sure, can you please remove stripe as enrollment method for this course and check again. let us know whether the issue is still there.

Hi @moumitahalder 
I uninstalled and installed again ;-) 
The same :( 
![image](https://github.com/dualcube/moodle-enrol_stripepayment/assets/5038301/ba2655da-6401-4436-984c-fe131ad8d98a)

**Comment by moumitahalder** [comment]
Hi,

Please refrain from uninstalling the plugin.

Instead, remove this enrollment method and utilize another enrollment method to observe the display.
