### ISSUE TITLE
$0 Purchases Not Syncing with Stripe

### ISSUE THREAD

**Issue by mayflowercreative** [dualcube/moodle-enrol_stripepayment#146]
We offer scholarships on some of our courses and use coupon codes to discount those courses to $0 for scholarshipped students. We are needing to see a record in Stripe of all purchases, even those with a $0 balance so we can get an accurate count of enrollments and scholarships. It appears that when a coupon code is used to discount a course to $0, the plugin bypasses the Stripe interface entirely and just enrolls the student in the course. This means we aren't able to get the data we need in Stripe. Part of the issue is that we're using Stripe to send data about enrollments to our CRM and trigger automated welcome emails to new students. Is there a way to get $0 course enrollments to sync with Stripe?

**Comment by moumitahalder** [comment]
Hi @mayflowercreative , Since the order total is $0, no payment was made. Stripe will only display transactions in their history if a payment was actually processed.
