### ISSUE TITLE
Multiple redemptions of coupon not prevented in free enrollment case

### ISSUE THREAD

**Issue by jimcrammond** [dualcube/moodle-enrol_stripepayment#147]
In amd/stripe_payment.js there is code to disable the payment button and show “please wait” after it is pressed. This prevents the user pressing it again while waiting for the transaction to complete. 

However, there is no such protection for the free enrollment case and the user can keep clicking the button multiple times while waiting for the transaction to complete. This results in multiple redemptions of the coupon ocuuring for one enrollment and for a limited use coupon that is a problem.

The solution is simply to disable the get_card_zero_cost button on click (and show the please wait message) in the same way as done for the buyBtn.

**Comment by moumitahalder** [comment]
Hi, we've just released an update with the fix. Please ensure you've installed the latest version of the plugin, 3.4.8 (2024082100), and check again.
