### ISSUE TITLE
Exeption - Call to a member function js_call_amd() on null

### ISSUE THREAD

**Issue by aalcaine** [dualcube/moodle-enrol_stripepayment#148]
<img width="1336" alt="Captura de pantalla 2024-08-20 a les 16 28 37" src="https://github.com/user-attachments/assets/6d5d3169-ffca-4174-b344-2c75be232532">

<img width="1345" alt="Captura de pantalla 2024-08-20 a les 16 29 12" src="https://github.com/user-attachments/assets/a788db2f-c9d7-4542-99f7-47d622285704">

Using Moodle 4.3.5+ Build 20240705.

Any idea on how to solve it? :)

Thank you!

**Comment by moumitahalder** [comment]
Hi , we've just released an update with the fix. Please ensure you've installed the latest version of the plugin, 3.4.8 (2024082100), and check again.
