### ISSUE TITLE
Not possible to use this plugin behind a proxy

### ISSUE THREAD

**Issue by timhunt** [dualcube/moodle-enrol_stripepayment#15]
We have a HTTP proxy, which is currently getting in the way of using this plugin.

It seems that Stripe only added Proxy support to their PHP library in March 2016 https://github.com/stripe/stripe-php/pull/234, but if I am reading the git history correctly, the contents of the 'Stripe' folder in this repository is older than that.

Is it safe to upgrade to the latest version of the Stripe PHP library? If you can do that?

If you are able to do that, then I am happy to write the code to use Moodle's HTTP proxy settings ($CFG->proxyhost, $CFG->proxyport, etc) to set the right Proxy options for the Stripe API if necessary. (I think it is mostly a matter of copying this bit of code from lib/filelib.php https://github.com/moodle/moodle/blob/master/lib/filelib.php#L2816.)

Thank you.

**Comment by anthonyforth** [comment]
I have taken over from Tim on the project he was working on.  We'd be grateful if the Skype library can be updated.  We will need proxy support when we start using the plugin in anger in the next few weeks.  I am happy to write the code once the plugin has been updated (as per Tim's original offer).

Thanks

**Comment by parthajeet** [comment]
Hello Anthony,

Thanks, we have updated the stripe library in github. So you can download from here and make changes.

Let me know if any thing else is needed.

Regards,
Parthajeet~
