### ISSUE TITLE
After updating the plugin, text inputs turned red.

### ISSUE THREAD

**Issue by tonytonyistony** [dualcube/moodle-enrol_stripepayment#152]
After updating the plugin, the text in input fields are now bright red.

![image](https://github.com/user-attachments/assets/dc058fc8-85fa-4216-a543-53572ae60119)

The onyl way I have been able to fix this is applying the follow CSS change.

```
StripeElement input[placeholder], [placeholder], [placeholder] {
	color: black !important;
}
```
Any insight?

**Comment by moumitahalder** [comment]
We have added the fix in our GitHub repo. So kindly download the plugin from here and check.

**Comment by tonytonyistony** [comment]
@moumitahalder After updating Moodle the issue returned. Re-inputting the code above fixed the issue again.

![image](https://github.com/user-attachments/assets/e3cd764b-d870-4355-8a54-ebcecdca6051)

![image](https://github.com/user-attachments/assets/552fb5ff-a037-46bc-9449-59e441d0b967)

**Comment by moumitahalder** [comment]
Hi, as you have updated moodle, hence the plugin reverted back to it's official released version. 

As we haven't released the update yet, so please use the GitHub version.

**Comment by moumitahalder** [comment]
@tonytonyistony, as you have updated Moodle, so it will also install the current version of the plugin uploaded in Moodle org.

So, by using the GitHub version, you will have the fixed version.
