### ISSUE TITLE
Add an option to ask for a Billing address

### ISSUE THREAD

**Issue by timhunt** [dualcube/moodle-enrol_stripepayment#17]
Another change I would like to make:

In the Stripe documentation (https://stripe.com/docs/checkout#highly-recommended) they strongly recommend you turn on the options for data-zip-code and data-billing-address.

I would like to add an option for this (probably two checkboxes in settings.php, and then change enrol_page_hook and enrol.html to use the value of those settings).

Should we also extend the enrol_stripepayment database table, to strore the address? I guess not, because that would be a potential security risk. We store things like the transaction id, and they could be used to look up these details in the Stripe dashboard, if you need to access them.

Is it OK if I make this change? Thank you.

**Comment by parthajeet** [comment]
Hi Tim,

Thanks again for your continued support! Yes, please go ahead with the change and about extending the table enrol_stripepayment, you are correct. It shouldn't be extended.

Let me know if you need any assistance.

Thanks and Regards,
Parthajeet~

**Comment by timhunt** [comment]
Just an update that I have made some progress. I have written some code which you can see at https://github.com/timhunt/moodle-enrol_stripepayment/compare/wip14...wip17, but I have not tested it yet. Hopefully it will be ready for me to submit it to you next week.
