### ISSUE TITLE
Capability with Moodle 3.5

### ISSUE THREAD

**Issue by ruiqian2g** [dualcube/moodle-enrol_stripepayment#20]
Hi there,

This is Noctis. 

I am currently using Stripe for my payment system. 

However, when I try to install the plugin for Moodle 3.5 via Bitnami Azure, I am having to following errors.

enrol_stripepayment
XML database file errors found

More information about this error

×Debug info: Errors found in XMLDB file: PATH attribute does not match file directory: enrol/stripepayment/db
Error code: ddlxmlfileerror
×Stack trace:
line 352 of /lib/ddl/database_manager.php: ddl_exception thrown
line 368 of /lib/ddl/database_manager.php: call to database_manager->load_xmldb_file()
line 594 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

Is there anything I should do prior to installing to plugin?

Best

**Comment by ruiqian2g** [comment]
Just remove install.xml, solved!

**Comment by parthajeet** [comment]
Hi!!
Please do not remove install.xml. Then the database won't get updated.

We have uploaded the latest version in here as well as on Moodle.org.
Please install the latest version.

Thank you.
