### ISSUE TITLE
Stripe payment plugin AND Stripe Connect

### ISSUE THREAD

**Issue by grunam** [dualcube/moodle-enrol_stripepayment#22]
Hi, 

Stripe moodle plugin does it manage Stripe Connect with Standard Accounts ?

https://moodle.org/plugins/enrol_stripepayment
https://stripe.com/docs/connect/standard-accounts

I must integrate partial payment for contributor teacher (90% of the price of his course) and Moodle Formedlive e-learning platform (10% of the price of the course).

Kind regards.

**Comment by moumitahalder** [comment]
@grunam, thanks for getting in touch with us.  
Yes,  our plugin Stripe supports Standard Accounts. 

Now, our plugin receives the payment from customer and sends the full money to admin.
Now can you please explain the partial payment flow that you need so we can help you out accordingly.
