### ISSUE TITLE
Removing Remember Me check box from credit card form. 

### ISSUE THREAD

**Issue by Blacksheeprules** [dualcube/moodle-enrol_stripepayment#23]
Could someone please tell me how to remove the remember me check on the credit card input window. Ideally, I would like to use css in moodle, but a code change will work. 
Thanks so much in advance for your help. 

Regards,

Mark

**Comment by parthajeet** [comment]
Hello,

In enrol.html page (https://github.com/dualcube/moodle-enrol_stripepayment/blob/master/enrol.html)

in the script add data-allow-remember-me="false" to remove remember me checkbox. Hope this helps.

Stripe Reference Doc - https://stripe.com/docs/checkout

Thanks,
Parthajeet~

**Comment by Blacksheeprules** [comment]
Thanks for the help. Do you know where the script is in the moodle plugin?

**Comment by parthajeet** [comment]
Yes, it's under your_moodle_folder/enrol/stripepayment/enro.html

**Comment by Blacksheeprules** [comment]
Thank-you very much!

**Comment by Blacksheeprules** [comment]
Thanks again. It worked!

**Comment by parthajeet** [comment]
Glad to know it worked. Welcome.
