### ISSUE TITLE
Error on charge.php

### ISSUE THREAD

**Issue by OINet** [dualcube/moodle-enrol_stripepayment#24]
Hello: 

I installed the last version of Stripe payment for Moodle but it is not working . My Moodle version is 3.6.2. I introduce the credit card number and a green OK mark shows up when I confirm the payment, but then I get a HTTP 500 error when page .../charge.php shows up.

Can you help me?

Thank you very much in advance.

**Comment by parthajeet** [comment]
Please download the latest uploaded plugin from Moodle.org and use that. We did not change the version in our latest upload so you will not get any update notification.
Thank you.

**Comment by OINet** [comment]
Hi,

Thank you very much for your response, but I just installed the latest plugin and it is still not working. Same error. Any other suggestions?

Thanks

**Comment by parthajeet** [comment]
Please share your FTP credentials. I will debug the issue.
Thank you.

**Comment by OINet** [comment]
Thank you, where can I send them privately?

**Comment by parthajeet** [comment]
You can send it on suman.d@dualcube.com.

Thanks

**Comment by parthajeet** [comment]
We have fixed it on your server.
Thank you.

**Comment by OINet** [comment]
Thank you so much!! It is working now.

**Comment by parthajeet** [comment]
Glad to know its working.
Thanks.

**Comment by ideaRed** [comment]
Hi, 

We have the same problem with charge.php. Our moodle version is 3.1.12 and we have installed the latest version of the stripe plugin.

I introduce the test credit card number (4000007240000007) and a green OK mark shows up when I confirm the payment, but then I get a HTTP 500 error when page .../charge.php shows up.

Could you solve the error, please?

Thanks,
