### ISSUE TITLE
Error on charge.php

### ISSUE THREAD

**Issue by ideaRed** [dualcube/moodle-enrol_stripepayment#25]
Hi, 

We have the same problem with charge.php. Our moodle version is 3.1.12 and we have installed the latest version of the stripe plugin.

I introduce the test credit card number (4000007240000007) and a green OK mark shows up when I confirm the payment, but then I get a HTTP 500 error when page .../charge.php shows up.

Could you solve the error, please?

Thanks,

_Originally posted by @ideaRed in https://github.com/dualcube/moodle-enrol_stripepayment/issues/24#issuecomment-485737360_

**Comment by parthajeet** [comment]
Please share your FTP credentials so that we can debug and fix the issue on your site.

Thank you.

**Comment by ideaRed** [comment]
Hi,

Can I send the credentials privately?

Thanks.

**Comment by parthajeet** [comment]
Please email us at admin@dualcube.com

Thank you.
