### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by muzetik** [dualcube/moodle-enrol_stripepayment#26]
Hi,

I would like to translate this module in Frence, I have created the lang/fr/enrol_stripepayment.php with the new strings but nothing appears, what am I missing ?

Thanks.

**Comment by LouisNatagora** [comment]
Have you purged the Moodle cache?

**Comment by trideepdm** [comment]
Dear @muzetik 

@LouisNatagora is right. You have purged the moodle cache to reflect your custom strings.

Thank you.
