### ISSUE TITLE
100% COUPON discount gives error message

### ISSUE THREAD

**Issue by EducatedSingles** [dualcube/moodle-enrol_stripepayment#33]
When I try to apply a 100% discount coupon I get the error message below

Exception - This value must be greater than or equal to 1.

It should just set the amount to 0 and enrol the user in the course. I hope you fix it soon.

Kind regards
Finn
Site: https://elearning.gugin.com

**Comment by trideepdm** [comment]
This issue will be fixed on our next update. Thank you.
