### ISSUE TITLE
Direct $_POST variable using

### ISSUE THREAD

**Issue by OlenaTatarintseva** [dualcube/moodle-enrol_stripepayment#34]
Hello,

Thank you for your hard work with the plugin.

I noticed some direct $_POST variable usages in the code. It is good practice in Moodle to use required_param() and optional_param() instead.

Files:
enrol/stripepayment/charge.php:42
enrol/stripepayment/charge.php:71
enrol/stripepayment/enrol.php:95
enrol/stripepayment/enrol.php:96
enrol/stripepayment/enrol.php:97
enrol/stripepayment/free_enrol.php:63

Best regards,
Olena Tatarintseva

**Comment by trideepdm** [comment]
Thank you for your suggestion. We replace $_POST into our next update.

**Comment by trideepdm** [comment]
Thank you for your suggestion. We replace $_POST on our next update.
