### ISSUE TITLE
charge.php does not sanitize the message content

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_stripepayment#4]
On error, the charge.php send an email to the admin. The message contents consists of the raw $_POST values which might be a security risk. Can you please make sure to use something like

```
    foreach ($data as $key => $value) {
        $message .= s($key) .' => '. s($value)."\n";
    }
```

or even better something like `json_encode($data)`.

**Comment by timhunt** [comment]
This one also seems to be fixed: https://github.com/dualcube/moodle-enrol_stripepayment/blame/master/charge.php#L279
