### ISSUE TITLE
Only support Credit Cards? 

### ISSUE THREAD

**Issue by sam-suresh** [dualcube/moodle-enrol_stripepayment#40]
First of all, thank you for this awesome plugin. 

Does it only support Credit Cards? As Stripe support local banks is this already in this plugin? 

I only see Credit Card options showing although my Stripe account has local bank payment enabled. 

Thank you

**Comment by sumandualcube** [comment]
Dear Sam,
Thanks for your appreciation.
This plugin only supports credit card payment for now. We have not added any other support to this plugin.
Thank you.
