### ISSUE TITLE
Did not auto-register student

### ISSUE THREAD

**Issue by mattmetzgar** [dualcube/moodle-enrol_stripepayment#41]
I used the plugin for a class of 30.  For one student, it charged them successfully in Stripe, but did not automatically enroll them in Moodle.
I contacted Stripe, and they said the code needs to be updated.  They sent me the attached screenshot.
![MoodleStripe](https://user-images.githubusercontent.com/55600169/86818471-6e632a80-c054-11ea-8a7d-2876decd65f1.png)

**Comment by trideepdm** [comment]
Dear,

From the attached screenshot it's clear that the payment was successful. So can you please specify what exactly error is shown to you? 

Thank you.

**Comment by mattmetzgar** [comment]
The payment went through, but it did not auto-enroll the student into the course in Moodle.  I had to manually enroll the student.

This just happened again yesterday with a new class.

**Comment by purnendudash** [comment]
Hello @mattmetzgar 

Can you please check the issue with our latest release and let us know.
