### ISSUE TITLE
Strip products and prices! 

### ISSUE THREAD

**Issue by sahedbs23** [dualcube/moodle-enrol_stripepayment#43]
Do you have any option for `create and use products and prices` in strip ?
How can i add subscription based courses ?

**Comment by purnendudash** [comment]
Hello @sahedbs23,

Thanks for your query. I am afraid, our plugin just enables the Stripe payment gateway for moodle courses to sell. I am afraid, our current version of the plugin does not support subscription, however, will add this in near future.
