### ISSUE TITLE
Apply code button not clickable

### ISSUE THREAD

**Issue by saraiyaaditya** [dualcube/moodle-enrol_stripepayment#44]
Even if the user enters the correct coupon code the apply code button is not clickable.

**Comment by rituparnagithub** [comment]
@saraiyaaditya 
Hi ,
We have checked the issue you mentioned, however we didnot find any such problem.

**Comment by rituparnagithub** [comment]
Hi @saraiyaaditya ,  https://share.getcloudapp.com/OAuJgmWp
