### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by esmoyer** [dualcube/moodle-enrol_stripepayment#5]
No matter what I try, when I go to add Stripe Payment to the Course Enrollment Method, it returns a "Page not Found" error. Any insight to this? I have tried searching around and am not able to find much about it. I am on the latest Moodle 3.0. (Posted in Moodle comments as well) Thanks for any advice!

**Comment by parthajeet** [comment]
Hello,

Can you please turn the debugging mode on and provide us a screenshot of the error page as well as the enrollment method page (when you are trying to add the Stripe Payment method to the course).

Regards,
Parthajeet~

**Comment by esmoyer** [comment]
Thanks for the response! The first image is our enrollment option page where I go to select Stripe, but as soon as I do it now just goes back to the course listing page with the error (second picture). Thanks again for any insight!

![enrol select](https://cloud.githubusercontent.com/assets/17444085/14233530/20dbe3b2-f991-11e5-8ffb-1ad199773433.PNG)
![error](https://cloud.githubusercontent.com/assets/17444085/14233531/24f4e35e-f991-11e5-9360-37a50846bb9e.PNG)

**Comment by esmoyer** [comment]
I did some digging and was able to get rid of the error in the picture, but when trying to add the Stripe as an enrollment method, it just goes back to the course listing like in the second picture, but now there is no error.

**Comment by parthajeet** [comment]
Thanks for the screenshot. We can see that the error is from some other source. It seems the error is due to file permission issue. Can you please check once that all the files are 644 and the directories are 755.

Regards,
Parthajeet~

**Comment by esmoyer** [comment]
Genius! That fixed it. Thank you!

**Comment by parthajeet** [comment]
Glad to know that this took care of your problem.

Regards,
Parthajeet~
