### ISSUE TITLE
Breaks Moodle - says I must change config to specify MariaDB

### ISSUE THREAD

**Issue by cliffbdf** [dualcube/moodle-enrol_stripepayment#64]
When I installed the plugin, the Moodle Admin system ran a check and produced an error saying that I needed to configure Moodle to use MariaDB instead of MySQL. Removing the plugin restored Moodle. I am using Moodle version 3.10.1, installed via Softactulous using the vanilla configuration, no other plugins added since installation and no site configurations changed.

**Comment by moumitahalder** [comment]
Hi @cliffbdf, thanks for getting in touch with us,

We have released an update of Stripe. Kindly update the plugin and let us know.
