### ISSUE TITLE
More than one instance causes error

### ISSUE THREAD

**Issue by sam-suresh** [dualcube/moodle-enrol_stripepayment#65]
Adding more than 1 stripe enrolment causes an error. 

ERROR 500. 

I've tested in 2 Moodle instances and same results. 

For example 1 Month USD 10 - enrolment instance 1
                      2 Months USD 20 - enrolment instance 2

This will result in Error 500. However the same concept works with PayPal enrolment method.

**Comment by CtanShard** [comment]
Hi,  I have been working with a client that is experiencing this problem as well.  Any course where we apply more than one stripe enrollment method ends up breaking the /enrol/index.php?id=x page.  The page displays error 500 until we disable one of the methods.   

Moodle 3.8.4

Stripe
3.2.1 (Build: 2020013100)
2020121401

**Comment by salar154** [comment]
Hello, I have been experiencing this same issue, in which, any course that I have more than one Stripe plugin enrollment method enabled, it gives an HTTP 500 internal server error. After multiple tests, I see that it only allows one Stripe plugin to be enabled at a time. I am even able to have two PayPal enrollment methods, and one Stripe; still works fine. It is purely when two stripe enrollment methods are enabled.

Moodle 3.9

Stripe
3.2.1 (Build: 2020013100)
2020121401

**Comment by andrewtam0077** [comment]
I also had an unexpected error that resulted in an HTTP 500 internal server error involving multiple Stripe plugin enrollment methods enabled. It functions properly with one Stripe plugin but only when one is enabled.

**Comment by moumitahalder** [comment]
Hi @sam-suresh, we will add support of the subscription payment module in our pro version.

**Comment by CtanShard** [comment]
Hi @moumitahalder I think the issue reported here is a bug in the stripe plugin.   We just want to add multiple 'Stripe Enrollment Methods' to courses.  If we add a second Stripe Enrollment in a course right now it breaks the enrollment page where Moodle shows users the payment options.
