### ISSUE TITLE
Accepts invalid card number

### ISSUE THREAD

**Issue by RyanNutt** [dualcube/moodle-enrol_stripepayment#7]
I was testing this and used one of the Stripe test card numbers `4100000000000019` which is supposed to come back as a declined card because of fraud. It appears to have been accepted, but when sent to the charge.php file in your plugin it came up with just the message `Error`.

**Comment by parthajeet** [comment]
Hello,

We have checked this issue. Its and error from the the strip payment gateway. The https://checkout.stripe.com/checkout.js is not validating the card number. The other incorrect cards are correctly validated by this js file except the card number 4100000000000019.
