### ISSUE TITLE
email field is not populated in Stripe transaction

### ISSUE THREAD

**Issue by mcwe** [dualcube/moodle-enrol_stripepayment#8]
When looking at the Stripe dashboard and transactions, the email field is empty and the email is instead submitted in the name field. Is there a way to make sure the email field get's populated properly for the purpose of receipt emails?

**Comment by parthajeet** [comment]
Hello,

Can you please provide us a screenshot of the transaction page where the email field is empty?

Regards,
Parthajeet~

**Comment by mcwe** [comment]
![screen_shot_2017-02-24_at_10_10_36_am](https://cloud.githubusercontent.com/assets/6810607/23308636/cafa21c6-fa79-11e6-9edf-71c9cc3a6ec0.jpg)

**Comment by mcwe** [comment]
![screen_shot_2017-02-24_at_10_10_36_am](https://cloud.githubusercontent.com/assets/6810607/23308672/efe74e32-fa79-11e6-9311-0ba40e77fb14.jpg)

**Comment by parthajeet** [comment]
We have updated the code for receipt_email. Please be advised it will only work for live transaction and not test / sandbox transaction. You can download the latest update from gituhub.

Regards,
Parthajeet
