### ISSUE TITLE
Error after payment

### ISSUE THREAD

**Issue by alexdebelka** [dualcube/moodle-enrol_stripepayment#82]
Hi! After I do a test payment I receive this error. (everything is fine until that stage) {"exception":"moodle_exception","errorcode":"invalidtoken","message":"Invalid token - token not found"}

How can I solve it?

P.S. I receive the payment in stripe, but my account is not enrolled, even if I have the stripe_enrollment option on.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/53542458/129344430-59aba127-05ae-40f0-866a-94ef35134e83.png">

**Comment by moumitahalder** [comment]
Hi @alexdebelka, please make sure you have added the token in your stripe's settings page. 
I am sharing the updated document to guide you further: https://dualcube.com/docs/stripe-payment-with-sca-and-coupon/#3-toc-title

**Comment by alexdebelka** [comment]
Thank you, it worked, but now this appears

<img width="899" alt="image" src="https://user-images.githubusercontent.com/53542458/129448095-0c7578fb-342d-4a17-8b4a-ae5ec5e867fe.png">

**Comment by purnendudash** [comment]
May I know the payment status on Stripe of this order.

**Comment by alexdebelka** [comment]
It is "succeed"

**Comment by alexdebelka** [comment]
Succeeded*

**Comment by cool-raju** [comment]
Hi @alexdebelka,
This is not an error. This is just a massage from moodle course. It takes a few seconds to get responsive from any payment gateways. Just continue it. You will successfully enrol on that course.
Thanks
