### ISSUE TITLE
Stripe payments and Moodle auto-enrolment

### ISSUE THREAD

**Issue by MarkBEATT** [dualcube/moodle-enrol_stripepayment#85]
Having had issues with PayPal in Moodle not allowing enrolment on our courses, we are now trying to use the Stripe Plugin by Dualcube. But we cannot work out why once paid, a student is not automatically enrolled and able to access their course that they have paid for. Payments  are coming through on Stripe just fine, but no automatic registration. 

![Stripe Payment error message_080921](https://user-images.githubusercontent.com/90335322/132534091-da2750da-486f-4d33-9d80-bb16c4587525.JPG)

**Comment by binaryflow** [comment]
Same issue happening with our Moodle deployment. Have we found a fix to this issue?

**Comment by purnendudash** [comment]
Kindly setup the API token on your Moodle Stripe settings page.

**Comment by binaryflow** [comment]
> Kindly setup the API token on your Moodle Stripe settings page.

Thank you for your response! We have the Stripe Secret Key, Stripe Publishable Key, and User Token set up and defined. We also double-checked to make sure that we had the correct tokens in place.

![image](https://user-images.githubusercontent.com/6186861/135491066-b2b85b23-17ac-481f-9248-39a30bb48940.png)

**Comment by purnendudash** [comment]
If the user token is set and website REST protocol is enabled it should work, otherwise need to debug via logging.
