### ISSUE TITLE
Issue with 100% Discount

### ISSUE THREAD

**Issue by hankhanna** [dualcube/moodle-enrol_stripepayment#89]
I have created a 100% discount code and when I try to use it to enroll in the course, it discounts the price onscreen and the button changes from saying "Buy Now" to "Enroll Now." However, when I try to click on the Enroll Now button, nothing happens. The expected response is that I would click on the button, it would enroll me in the course, and then take me to the course page. Nothing happens though. It's as if the button becomes disabled.

Please advise.

![Screen Shot 2021-10-25 at 2 54 05 PM](https://user-images.githubusercontent.com/8108188/138753908-060c398f-c198-4b08-9eeb-c8f6e771c876.png)

![Screen Shot 2021-10-25 at 2 54 16 PM](https://user-images.githubusercontent.com/8108188/138753953-c17d9c64-0f3c-4c88-8949-63b4eb8bbdda.png)

![Screen Shot 2021-10-25 at 2 54 30 PM](https://user-images.githubusercontent.com/8108188/138753971-df165ade-00bf-46fb-8f8a-4ae5892ddc19.png)

**Comment by cool-raju** [comment]
@hankhanna we have added a commit. Please check and let us know.

**Comment by tsprei** [comment]
Hi. I have the same problem. No action when you click de button "Enrol now". ¿Can I help with copying some info? Thanks.

**Comment by innsas24** [comment]
Hello! I have tested today, 3/27/2022 and the issue persists - the "Enrol" button remains inactive after a coupon code for 100% discount is entered.

**Comment by innsas24** [comment]
> @hankhanna we have added a commit. Please check and let us know.

Hello! I have tested today, 3/27/2022 and the issue persists - the "Enrol" button remains inactive after a coupon code for 100% discount is entered.
