### ISSUE TITLE
Course Title in Description

### ISSUE THREAD

**Issue by mcwe** [dualcube/moodle-enrol_stripepayment#9]
When exporting transactions from Stripe there is no identifier in the description field. Would it be possible to insert the course title in the description field?

ie: [COURSE_TITLE] instead of "Charge for Course Enrolment Cost."

Thank you for your help.

**Comment by parthajeet** [comment]
Hello,

Yes you can change the description. In charge.php line 120, edit the below code 

"description" => "Charge for Course Enrolment Cost.",

to

"description" => $course-fullname,

to display the course title / course fullname.

Hope it helps.

Regards,
Parthajeet~

**Comment by mcwe** [comment]
After inserting that code, the description field just shows the number "1". Not sure where to check for error message to see what's happening

**Comment by parthajeet** [comment]
Sorry for the typo it should be

**"description" => $course->fullname,**

and not 

"description" => $course-fullname,

Can you retry once with the above **bold** code.

Regards,
Parthajeet~
