### ISSUE TITLE
Error installing 3.3.2 on Moodle 3.11.6 (Build: 20220314)

### ISSUE THREAD

**Issue by indybyno** [dualcube/moodle-enrol_stripepayment#99]
Hi,

I get the following error while installing the latest plugin version (3.3.2) on my 3.11.6 moodle instance.

**Downloading enrol_stripepayment ... OK
Validating enrol_stripepayment ... Error
  [Error] Extracted file not found [{"file":"stripepayment\/.git\/refs\/tags\/"}] 
Installation aborted due to validation failure**

Thanks for your help in advance.

**Comment by moumitahalder** [comment]
Hi, please use the latest version of stripe plugin.
